### ISSUE TITLE
Problems installing pyabpoa

### ISSUE THREAD

**Issue by nriddiford** [christopher-vollmers/C3POa#2]
Hi, 

I'm trying to get C3POa setup on my mac but Im having problems installing `pyabpoa`:

```
python/pyabpoa.c:196:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyabpoa
  Running setup.py clean for pyabpoa
Failed to build pyabpoa
ERROR: Could not build wheels for pyabpoa, which is required to install pyproject.toml-based projects
```

I've tried re-installing `cython` before installing `pyabpoa` as suggested [here](https://github.com/yangao07/abPOA/issues/23) but this produces the same error. 

Any ideas?

**Comment by christopher-vollmers** [comment]
Hi,

Sorry for the slow response. I've been working on getting rid of pyabpoa. C3POa uses abpoa now. I'm not sure whether apboa install on a Mac either tbh. I really only have the time for testing this on Linux.
