### ISSUE TITLE
Difference in output between older and latest version

### ISSUE THREAD

**Issue by M-Dunnet** [christopher-vollmers/C3POa#5]
I have been using C3POa for a while now, and overall I think its great! 

Originally when I started I was using version 2.4.0, and this has worked well for me. I have recently tried the most up to date version. However, when I run it I get a very small number of consensus call reads. I've run the same fastq file (containing 4000 reads) with both versions and get very different results (see log files below). 

Using some print statements I've found that the issue seems to be in the `determine_consensus` function although I'm not too sure where to go from here, so any advice is greatly appreciated. 

C3POa version: v3 - It's over Anakin. I have the consensus!
new iteration
Total files to process: 1
Too short reads: 261 (6.53%)
No splint reads: 317 (7.92%)
Successful consensus reads: 158 (3.95%)
        158 consensus reads generated for UMI_Splint_1

C3POa version: v2.4.0
Total reads: 4000
No splint reads: 317 (7.92%)
Under len cutoff: 261 (6.53%)
Total thrown away reads: 578 (14.45%)
Reads after preprocessing: 3422

**Comment by christopher-vollmers** [comment]
Hi!

Happy C3POa has worked for you so far. 

The change to version 3 was mostly a change to enable live consensus calling. At least until the new dorado output format made that a lot harder. The output should definitely look the same.

Another change we made (ironically to make it easier to set up) is that a lot of dependencies are now installed into the C3POa folder by the setup script. Could you try running the setup script, then trying your comparison again?

chmod +x setup.sh
./setup.sh

That hopefully should fix it.

Best,
Chris

**Comment by M-Dunnet** [comment]
When I run setup.sh everything works fine except abPOA. 

I get an error when building abPOA-v1.4.1 (error: ‘for’ loop initial declarations are only allowed in C99 mode). I think this is because of an incorrect GCC version - I currently work on a shared server and I'm not too sure how to (or if I should) update this. 

Instead I downloaded a binary of abPOA-v1.4.2 and have been using this instead. Is this likely to be causing the issue?

Thanks,
Michael

**Comment by M-Dunnet** [comment]
Hi Chris, 

I have re-downloaded the binary of abPOA and everything seems to work perfectly now - looks like I originally used the wrong version. Thanks very much for your help!
